### ISSUE TITLE
Stiebel Eltron ISG Cooling Room Temperature Target not synced with  ISG

### ISSUE THREAD

**Issue by fabricekrebs** [pail23/stiebel_eltron_isg_component#102]
Hello,

I've an ISG Web. I've manually specified on the ISG the Target Room temperature to 22°. On HAS, the Stiebel Eltron ISG Cooling Room Temperature Target stay at 25°.

I try to change on the HAS the value for Stiebel Eltron ISG Cooling Room Temperature Target to 21.9°, but not changes was made on the ISG Gateway.

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/49933831/f43048eb-561d-456e-a1f2-7c8ec87315e6)

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/49933831/66612737-1cbe-4703-8478-b91610703f85)

**Comment by Chris909090** [comment]
Hello together :)
I have the same problem with the water temperature?

**Comment by pail23** [comment]
@fabricekrebs Your Servicewelt Screenshot shows Cooling Circuit 2. In the [Modbus Manual](https://www.stiebel-eltron.de/content/dam/ste/cdbassets/historic/bedienungs-_u_installationsanleitungen/ISG_Modbus__ed049b5c-79e9-4efa-a99c-7532a657e54a.pdf), there is no indication of a Circuit number. I'm using the registers 1514 and 1516. 
@Chris909090 @fabricekrebs Could you please install the latest release 2023.10 and download the diagnosis information. I have added a "system_parameters" entry which shows all the 15xx registers which are read. Is there any value correctly showing the temperature?

**Comment by Chris909090** [comment]
@pail23 
Thanks four your help!

As you could see in the diagnostic there is the value for the water temperature set to 41,2°C.
But in the servicewelt there are still 41°C.

Maybe here is a problem with the vslue? It iftenshows "32768". Are you able to reproduce the error?

Thanks for your time!

**Comment by Chris909090** [comment]
Sry here the images 
![Screenshot_20231016_222826_File Manager +](https://github.com/pail23/stiebel_eltron_isg_component/assets/39734863/e6ce5e09-2e30-476f-b1ea-0281aa2a6420)
![SmartSelect_20231016_222419_Edge](https://github.com/pail23/stiebel_eltron_isg_component/assets/39734863/6707efce-363a-44e6-bff6-51e3e18bdee0)

**Comment by Chris909090** [comment]
@pail23 
Were you able to do anything with what I told you?

**Comment by pail23** [comment]
@Chris909090 The modbus registers are matching the values in homeassistant.  I have no clue why servicewelt is showing a different value. What happens if you set the water temperature in Homeassistent to e.g. 50? Does the heat pump react?

**Comment by Chris909090** [comment]
OK I do not understand why but now it works I guess it was not your app but Stiebel Eltron itself

Thank you! :)
