### ISSUE TITLE
"Stiebel Eltron ISG Return Temperature" gets a wrong value

### ISSUE THREAD

**Issue by chrissi5120** [pail23/stiebel_eltron_isg_component#104]
Hi everyone,

"Stiebel Eltron ISG Return Temperature" seems to get wrong data, it is stuck between 29.1 and 29.5C°, depending on the compressor, if it is running or not.

There might be a field in Modbus, which is not picked up correctly?

**Comment by chrissi5120** [comment]
From the documentation:

511 ISTTEMPERATUR HK 2 x x x 0 90 2 °C r
512 SOLLTEMPERATUR HK 2 x x x 0 65 2 °C r
513 VORLAUFISTTEMPERATUR WP x x x MFG, sofern vorhanden 2 °C r
514 VORLAUFISTTEMPERATUR NHZ x x x MFG, sofern vorhanden 2 °C r

From code:

`            result[ACTUAL_TEMPERATURE_HK2] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )
            result[TARGET_TEMPERATURE_HK2] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )
            result[FLOW_TEMPERATURE] = get_isg_scaled_value(decoder.decode_16bit_int())
            decoder.skip_bytes(4)
            result[RETURN_TEMPERATURE] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )`

is the decoder.skip_bytes(4) on the correct position?

**Comment by pail23** [comment]
Hmm...
In my case, Flow Temperature as well as Return temperature is between ~18 and ~52 (when the heat pump is heating the water).
Flow Temperature is mapped to register 513 and Return Temperature is mapped to 516. 514 and 515 are skipped by the skip_bytes(4). In my case 515 and 517 do not contain any values.
Could you try to download the diagnosis information (Click on the 3 dots below "Device Information"). You will get a json file in which you find "system_values" towards the end. Does any of the registers contain the correct value?

**Comment by Padanian** [comment]
While return temperature is common for all type of devices, flow temperature depends whether MFG or any other type of NHZ is installed. All in all I would suggest to use 516 for return and 515 for flow temperature.
In the office I have one WP with HSBC and MFG and one with HSBC without MFG.
I'll try to understand whether it makes a difference.

**Comment by Padanian** [comment]
for unit without MFG

Protocol configuration: MODBUS/TCP, FC4
Slave configuration...: address = 1, start reference = 501, count = 20
Communication.........: 10.100.139.21, port 502, t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, input register table

-- Polling slave...
[501]: -32768
[502]: -32768
[503]: -32768
[504]: -32768
[505]: -32768
[506]: -32768
[507]: -39
[508]: 262
[509]: -32768
[510]: 131
[511]: -32768
[512]: -32768
[513]: -32768
[514]: -32768
[515]: -32768
[516]: 226
[517]: -28672
[518]: -32768
[519]: -32768
[520]: -32768

for unit with MFG
Protocol configuration: MODBUS/TCP, FC4
Slave configuration...: address = 1, start reference = 501, count = 20
Communication.........: 10.100.139.22, port 502, t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, input register table

-- Polling slave...
[501]: -32768
[502]: -32768
[503]: -32768
[504]: -32768
[505]: -32768
[506]: -32768
[507]: -4
[508]: 262
[509]: -32768
[510]: 88
[511]: -32768
[512]: -32768
[513]: 269
[514]: 264
[515]: -32768
[516]: 270
[517]: 300
[518]: 270
[519]: 88
[520]: 159

Clearly the flow temperature without MFG returns out of scale, unless it's a cascade with common manifold sensor.
Common manifold sensor in a cascade is optional.

I would recommend using 542/543, which works in all cases (for heat pump 1 in a cascade) +7 for each further unit in a cascade.

**Comment by pail23** [comment]
In my case 542/543 does not work (I have a WPM 3i). So we probably need to check if we have a valid value in 513 and read 543 only if this is not the case.

**Comment by Padanian** [comment]
Makes sense. WPM3i actually don't have 542/543, you're right. So I'll try to fix it.
