### ISSUE TITLE
[Feature Request] Power consumption on LWZ

### ISSUE THREAD

**Issue by northalpha** [pail23/stiebel_eltron_isg_component#107]
Like discussed in https://github.com/pail23/stiebel_eltron_isg_component/issues/51 i would like to see the energy consumptions but i was too excited that the "verdichterstarts" are now working that i did not catch this, so here once again my wish to implement following adresses on a LWZ, i think they are present on WPM based devices but now on LWZs.

```
      # Power consumption
      - name: "LWZ P-HEIZUNG-TAG"
        slave: 1
        address: 3021
        input_type: input
        unit_of_measurement: kWh
        device_class: energy
      - name: "LWZ P-HEIZUNG-SUMME MWh"
        slave: 1
        address: 3023
        input_type: input
        unit_of_measurement: MWh
        device_class: energy
      - name: "LWZ P-HEIZUNG-SUMME kWh"
        slave: 1
        address: 3022
        input_type: input
        unit_of_measurement: kWh
        device_class: energy
      - name: "LWZ P-WW-TAG"
        slave: 1
        address: 3024
        input_type: input
        unit_of_measurement: kWh
        device_class: energy
      - name: "LWZ P-WW-SUMME MWh"
        slave: 1
        address: 3026
        input_type: input
        unit_of_measurement: MWh
        device_class: energy
      - name: "LWZ P-WW-SUMME kWh"
        slave: 1
        address: 3025
        input_type: input
        unit_of_measurement: kWh
        device_class: energy
```

see pages 17ff on the modbus pdf

**Comment by M4tRiX92** [comment]
I would really appreciate to get the power consumption of the LWZ for heating, hot water and ventilation. :) If you need anything from my side - please ask. Thank you!

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/77054170/470ec6b5-03e0-4c3c-a72c-edc9b48589bb)

**Comment by northalpha** [comment]
> I would really appreciate to get the power consumption of the LWZ for heating, hot water and ventilation. :) If you need anything from my side - please ask. Thank you!
> 
> ![image](https://user-images.githubusercontent.com/77054170/273811115-470ec6b5-03e0-4c3c-a72c-edc9b48589bb.png)

okay wow ... which software version is your ISG running, i do not have these values, or another hidden secret URL?

**Comment by M4tRiX92** [comment]
ISG web v12.2.2
Info -> Energy Footprint.
LWZ 5s plus

how can I find the information like, 

- name: "LWZ P-HEIZUNG-TAG"
        slave: 1
        address: 3021

I think they will be needed for implementation right?

**Comment by northalpha** [comment]
Yes, these are the Modbus Registers to be read out. Normally they would be apppaer here in this document: https://www.stiebel-eltron.de/content/dam/ste/cdbassets/historic/bedienungs-_u_installationsanleitungen/ISG_Modbus__b89c1c53-6d34-4243-a630-b42cf0633361.pdf (or the german onyl one here: https://www.stiebel-eltron.de/content/dam/ste/cdbassets/historic/bedienungs-_u_installationsanleitungen/ISG_Modbus__ed049b5c-79e9-4efa-a99c-7532a657e54a.pdf)

**Comment by pail23** [comment]
The modbus registers 3022 - 3027 are already read by the integration. The corresponding entities are:
- Consumed Heating Today (3022)
- Consumed Heating Total (3023, 3024)
- Consumed Water Heating Today (3025)
- Consumed Water Heating Total (3026, 3027)
Since I don't own a LWZ I can't test it. Please let me know in case the values are reported incorrectly.

I did not find any registers to energy consumption of the ventilation. I case you can figure out the register, I'm happy to add it.

**Comment by M4tRiX92** [comment]
According StiebelEltron-Support: "The Mod Bus registers for these values are not yet available. The software is under development.
Unfortunately I can not give you a date of availability."

**Comment by maierei** [comment]
Hi guys,
I would also like to get the power consumption values. After looking into the above linked dcumentation I think we need the registers 3511 to 3516:
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/76878128/37a837d3-f1e4-4f7f-b6cd-f105287be0fe)
Or am I wrong?

Regards
Markus

**Comment by maierei** [comment]
Hi @pail23 ,

could you have a look at my last posting? Do you think this could be the way where we could get the data from?

Thanks
Markus

**Comment by pail23** [comment]
Hi @maierei 

The registers you provided are used for the WPM heatpumps. Those are already available in the component:
Consumed Heating Today (3511)
Consumed Heating Total (3512, 3513)
Consumed Water Heating Today (3514)
Consumed Water Heating Total (3515, 3516)

The same entities are already available for the LWZ heatpump (using different registers, see above). The only thing which is missing is the energy consumption for the ventilation. In case you know the corresponding registers for the ventilation for the LWZ heat pumps, I would be very happy to know them.
