### ISSUE TITLE
Add SG-Ready Toggle

### ISSUE THREAD

**Issue by tmb80c** [pail23/stiebel_eltron_isg_component#11]
ISG Plus supports SG-Ready for WPM (according to Stiebel Eltron Software Dokumentation for modbus TCPIP) 
Modbus Addresses R/W holding registers
4001:  turn SG-Ready on/off
4002:  SG-Ready contact 1
4003: SG-Ready contact 2

**Comment by pail23** [comment]
Implemented in V0.3

**Comment by tmb80c** [comment]
Thank you,

I can confirm that in V0.3 the UI shows the correct state (2 in my case). I can also confirm through ISG web font end that I can turn Energy Management on / off (address 4001). So writing into a register works in general.

However Contact 4002 / 4003 are both in "on" state in gui while for state 2 (Programm/Automatic mode) both should be "off".

I can toggle the switches in the UI but this does not cange the SG-Ready state in the heat-pump.

**Comment by xylone** [comment]
Just curious: What can you do with this?
Is it a way to control the heatpump from within HA? (Change FEK target temperature, system state etc etc)

**Comment by tmb80c** [comment]
SG-Ready can be used in connection with a solar system. Instead of exporting solar generated electricity to the grid, HA could set the heat pump into an accelerated production mode (increasing heating and water temp by user predefined values, see heat pump manual). Usually my inverter would need a zigbee device and a smart device connected to the heat pump to control the inputs. This HA modbus ISG integration eleminates such additional hardware and provides more control through HA. Obviously I also need a similar integration for my inverter which is also modbus tcp enabled (Solaredge).

**Comment by xylone** [comment]
Ahhh that sounds nice! 
So how does it work? What do the switches do?
I know when I produce too much (ie send to the grid), so I could turn on the boiler heating.

**Comment by xylone** [comment]
I already found the answer in the documentation (I think) (added for future readers):
8.2.1 Operating states

Depending on the switching, the appliance can execute the fol-
lowing operating modes:

Operating state 1
Switching (input 2/input 1): (1/0)
- Lowest temperatures, cf. standby level (see operating and
installation instructions for the connected appliance)
- Frost protection is assured
Operating state 2
Switching (input 2/input 1): (0/0)

- Automatic / Programmed mode (see operating and installa-
tion instructions for the connected heat pump)

Operating state 3 (accelerated mode)
Switching (input 2/input 1): (0/1)
- Accelerated mode with increased values for heating and
DHW temperature

- You can set the increased values for heating and DHW tem-
perature mode under SETTINGS / ENERGY MANAGEMENT

Operating state 4
Switching (input 2/input 1): (1/1)

- Immediate switch to maximum heating and DHW tempera-
ture values

**Comment by xylone** [comment]
Still a bit unsure what the switched do.... 
I tried to enable the SG-Ready, with both input switches turned on (already default selected) but the heat pump does nothing.

**Comment by cm86** [comment]
I also tried to set the sg ready state via the switches. 
But it's not working.

Any advice for this?!

Mit freundlichen Grüßen 
Chris
