### ISSUE TITLE
Breaking change since HA 9.1

### ISSUE THREAD

**Issue by JulianPSLearner** [pail23/stiebel_eltron_isg_component#114]
## Version of the custom_component
0.3.0
-->

## Configuration

```yaml

Installation via HACS

```

## Describe the bug
This morning I upgraded to HA 2023.9.1. 
Since the update was in place suddenly i can't see any sensor data anymore :(
I received this warning:
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/79222321/0a26ca2c-f470-427f-839e-de1637dd9839)

Further details:
Home Assistant 2023.9.1
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230908.0 - latest

## Debug log

I activated "    custom_components.stiebel_eltron_isg: critical" but nothing was plotted in the logs.

**Comment by pail23** [comment]
This should be fixed in the release 2023.9 of the Stiebel Eltron ISG component.

**Comment by DaZeller** [comment]
> ## Version of the custom_component
> 
> 0.3.0 -->
> ## Configuration
> 
> ```yaml
> Installation via HACS
> ```
> 
> ## Describe the bug
> 
> This morning I upgraded to HA 2023.9.1. Since the update was in place suddenly i can't see any sensor data anymore :( I received this warning: ![image](https://user-images.githubusercontent.com/79222321/266778770-0a26ca2c-f470-427f-839e-de1637dd9839.png)
> 
> Further details: Home Assistant 2023.9.1 Supervisor 2023.08.3 Operating System 10.5 Frontend 20230908.0 - latest
> ## Debug log
> 
> I activated " custom_components.stiebel_eltron_isg: critical" but nothing was plotted in the logs.

... same here.

**Comment by DaZeller** [comment]
> This should be fixed in the release 2023.9 of the Stiebel Eltron ISG component.

Super! I'm looking forward to it. Have the same issue here.

Thanks for your dedication!

**Comment by JulianPSLearner** [comment]
I renamed multiple entities of my Wärmepumpe. When I remove the Code from the custom folder component and replace it with the New one - will they all be resetted and there fore renamed? Or is there a netter way to Update?

**Comment by artspb** [comment]
Thanks for the prompt fix!

**Comment by JulianPSLearner** [comment]
One Bug seems to be there. I can not change the Fan Level :( The sensor isn't Provided anymore. This Was my Main Feature :/ Any Chance to fix that? 
![Screenshot_20230910-204525](https://github.com/pail23/stiebel_eltron_isg_component/assets/79222321/34394506-dba7-4b7b-ad5d-464c72129bdd)
@pail23

**Comment by pail23** [comment]
@JulianPSLearner Great you habe eben able to fix it.

Yes, I habe used the card. Many thanks. Thies was highly appreciated. 🙏
