### ISSUE TITLE
Add read SG-Ready state

### ISSUE THREAD

**Issue by tmb80c** [pail23/stiebel_eltron_isg_component#12]
Read Input Register at address 5001
sg.ready.state = 
   state 1 (antifreeze / standby)
   state 2 (normal automatic or programm mode)
   state 3 (accelerated with increased heating and warmwater temp)
   state 4 (max heating and warm water)

**Comment by pail23** [comment]
Implemented in V0.3

**Comment by cm86** [comment]
Hello,
could it also be possible to set the state via home assistant?!

Mit freundlichen Grüßen 
Chris
