### ISSUE TITLE
Humidity

### ISSUE THREAD

**Issue by spielkind1611** [pail23/stiebel_eltron_isg_component#129]
Unfortunately, the humidity displayed for me is 0 percent. 
Is this the following register? :

22 EXTRACT AIR HUMIDITY

If not, is it possible to add this value for the LWZ devices?

Thanks!

**Comment by northalpha** [comment]
i think it is called `ABLUFTFEUCHTE` in german, right? So this is only possible for `nur bei LWZ 304/404/504/Trend` LWZ

**Comment by spielkind1611** [comment]
Yes, that's the register I mean. 
I have a LWZ 404 that's why I'm asking

The entity in the integration is exactly this register or is it a different one?

**Comment by pail23** [comment]
I have added the `Extract air humidity` sensor in 2023.10.1

**Comment by spielkind1611** [comment]
Thx it works!
