### ISSUE TITLE
Heating values are not correct for WPL09 and ISG Plus 12.2.0

### ISSUE THREAD

**Issue by ViktorLoew** [pail23/stiebel_eltron_isg_component#133]
## Version of the custom_component
ISG Plus 12.2.0 version
WPL 09 ICS classic

## Describe the bug
I get from the integration of all heating values as 32768. What can be the reason for that behaviour?
I tried to read the value from a Modbus tool and i got the same value

sensor.stiebel_eltron_isg_consumed_heating_todayStiebel Eltron ISG Consumed Heating Today 
| 32768 | (thats the Vlaue
state_class: total_increasing unit_of_measurement: kWh device_class: energy icon: mdi:lightning-bolt friendly_name: Stiebel Eltron ISG Consumed Heating Today
Stiebel Eltron ISG Consumed Heating Today
32768	state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
icon: mdi:lightning-bolt
friendly_name: Stiebel Eltron ISG Consumed Heating Today

**Comment by pail23** [comment]
Would you mind uploading the diagnose information? This would help to analyze the issue. Thanks!

**Comment by Padanian** [comment]
Please try again now. Pull request #177 tackles this issue.
