### ISSUE TITLE
Add Switch to change heat pump operating mode

### ISSUE THREAD

**Issue by tmb80c** [pail23/stiebel_eltron_isg_component#14]
Address 1501 (R/W) can change the operating mode. This can be helpful to implement in HA a vacation scene.

**Comment by pail23** [comment]
Added in V0.4

**Comment by xylone** [comment]
I tried to use this, but it doesn't seem to work.
I saw a register write for 1500 (heatpump) and for 1000 (air something) in the code. 
Which one is 'exposed' to HA?
