### ISSUE TITLE
[FEATURE] Add Presets to Climate-Entity

### ISSUE THREAD

**Issue by guevara777** [pail23/stiebel_eltron_isg_component#143]
**Is your feature request related to a problem? Please describe.**
I would like to contral my heat-pump via a tile-card or the newly added climate-pop-up. I can control the set-point-temperature via these, but i´m not able to change program modes. This should be possibly via [Preset-Modes](https://developers.home-assistant.io/docs/core/entity/climate/#presets)

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/5d22cfa4-2243-41eb-9a07-e60bbebbdc6f)

**Describe the solution you'd like**
Add the following Presets to the climate-entity of the heat-pump

**Predefined Presets**
- Preset "Eco" -> Switch to "Program Mode: Eco" (german = Eco-Betrieb)
- Preset "Comfort" -> Switch to "Programm Mode: Comfort" (german = Komfortbetrieb)

**Custom Presets**
- Preset "Program" -> Switch to "Program Mode: Program" (Icon = same Icon as "Auto"-HVAC-Mode, german = Programmbetrieb)
- Preset "Water Heating" -> Switch to "Program Mode: Water Heating" (Icon = mdi:water-thermometer, Warmwasserbetrieb)
- Preset "Emergency" -> Switch to "Program Mode: Emergency" (Icon = mdi:alert, german = Notbetrieb)
- Preset "Ready" -> Switch to "Program Mode: Ready" (Icon = mdi:snowflake-thermometer, german = Bereitschaftsbetrieb)

**Describe alternatives you've considered**
The Preset-Mode is already usable via an select-entity. This feature would just lead to more comfort in changing the settings.

**Additional context**
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/c06ebfb5-0038-42f0-b72b-bfbf66f59e06)

The Pop-Up would like this:
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/2827bdb4-a7c5-4e76-87a7-349b7f8bcea4)

And a tile card like this:
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/e15dcb7e-c031-45c5-a9a2-72b325e7dfd8)

**Comment by pail23** [comment]
Implemented in 2024.1. Please test the implementation and provide your feedback here.

**Comment by guevara777** [comment]
Thank you so much. I can confirm that it´s working fine 💯 

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/2e5e99cb-b5fb-452c-97f9-5406314ce36c)
