### ISSUE TITLE
 sensor.stiebel_eltron_isg_produced_heating_today Error

### ISSUE THREAD

**Issue by doubleus61** [pail23/stiebel_eltron_isg_component#153]
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:288
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 28. November 2023 um 22:25:10 (1 occurrences)
Last logged: 28. November 2023 um 22:25:10
Entity sensor.stiebel_eltron_isg_produced_heating_today from integration stiebel_eltron_isg has state class total_increasing, but its state is not strictly increasing. Triggered by state 67 (68.0) with last_updated set to 2023-11-28T21:24:56.964769+00:00. Please create a bug report at https://github.com/pail23/stiebel_eltron_isg_component/issues

## Configuration

No YAML configuration
```yaml

Add your logs here.

```

## Describe the bug

I fond the bug loking into the logger output.

**Comment by pail23** [comment]
This is problably a stange one off situation. Please let me know in case you see this more often.

**Comment by Padanian** [comment]
sensor.stiebel_eltron_isg_produced_heating_today does not always increase. It resets at midnight.

**Comment by Padanian** [comment]
Please try again now. Pull request https://github.com/pail23/stiebel_eltron_isg_component/pull/177 tackles this issue.

**Comment by pail23** [comment]
Should be solved in 2024.2

**Comment by pail23** [comment]
Please don't used the sensor.stiebel_eltron_isg_produced_heating_today sensor anymore and swith to sensor.stiebel_eltron_isg_produced_heating.
