### ISSUE TITLE
Dewpoint HK1 not available

### ISSUE THREAD

**Issue by Mappenhei** [pail23/stiebel_eltron_isg_component#154]
It seems the current config provides only dewpoint from modbus adress 506 which my heat pump does not provide. But I have a FEK which provide the dewpoint temperature related to HK1. 

Unfortunately I couldn’t find the actual used modbus address in this integration. Could you be so kind and check this? Thanks in advance.

<img width="1180" alt="image" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/124632181/540c0dd5-dd27-4cf4-9dd0-20a8771729fc">

**Comment by pail23** [comment]
Implemented in 2024.1. Please test the implementaiton and provide your feedback here. Thanks!

**Comment by Mappenhei** [comment]
Sorry about my late response. Dewpoint HK1 is now visible. Many thanks
