### ISSUE TITLE
Produced heating / Consumed Heating Energy truncated to integers

### ISSUE THREAD

**Issue by jeffjsmith33** [pail23/stiebel_eltron_isg_component#159]
This is not really a bug, but it would be an improvement.  The Stiebel Eltron ISG interface does show the heating generated and consumed values with three decimal points but the integration seems to give just the integer value.  It would be nicer if the value was given with a little more precision.

**Comment by guevara777** [comment]
This should be impossible right now. This integration communicates via modbus with the ISG. 

Stiebel Eltron does **_NOT_** offer modbus registers for the decimals the "consumend" and "produced"-sensor. I already had contact with their support and they confirmed that this registers aren`t there at the moment.

The only way to get these values could be via a scraper the "reads" the values from the isg-web-interface. I don`t think that this would be a good solution.

**Comment by jeffjsmith33** [comment]
I understand - and thank you for following this up.  Stiebel Eltron seem to have a very backward view of how useful smart home technology is, and their software seems to have stayed in the 1970’s almost.  I think they are missing the point and how important this aspect of their product is.

**Comment by guevara777** [comment]
i can not say anything bad about stiebel eltron. Maybe they do not have the best software, but the open and well documented modbus-protocol is great for controlling your heat pump via home assistant. i think it is no big deal to not have decimals of your energy consumption.

**Comment by pail23** [comment]
Closed because it can't be implemented using the current modbus interface of the Stiebel Eltron ISG.
