### ISSUE TITLE
Humidity is shown 0%

### ISSUE THREAD

**Issue by jaysus82** [pail23/stiebel_eltron_isg_component#174]
Hi, I just installed HA and your Integration and everything seems fine, just the humidity value is shown as 0%. The extract humidity is correct. 

![Screenshot_20240115_222048_Home Assistant](https://github.com/pail23/stiebel_eltron_isg_component/assets/156689299/308e4e46-3ab7-4a2b-97b7-c785bda39f97)

I am new to home assistant and running it in a container on a synology NAS. If you need more information, let me now, i'll try my best

**Comment by pail23** [comment]
Would you mind uploading the diagnostic information:
<img width="250" alt="image" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/13279715/ab44e9ec-1884-46b0-a8f5-b4f5cea095b2">

**Comment by jaysus82** [comment]
Of course not, thanks for the hint where to find it. Here you are.
[stiebel_eltron_isg-027ef4be412723f03f297fffa62728b2-Stiebel Eltron ISG-7c3f43fccbf06c779de2b36cc2455d04.json.txt](https://github.com/pail23/stiebel_eltron_isg_component/files/13947109/stiebel_eltron_isg-027ef4be412723f03f297fffa62728b2-Stiebel.Eltron.ISG-7c3f43fccbf06c779de2b36cc2455d04.json.txt)

**Comment by jaysus82** [comment]
Of course not, thanks for the hint where to find it. Here you are.
[stiebel_eltron_isg-027ef4be412723f03f297fffa62728b2-Stiebel Eltron ISG-7c3f43fccbf06c779de2b36cc2455d04.json.txt](https://github.com/pail23/stiebel_eltron_isg_component/files/13947137/stiebel_eltron_isg-027ef4be412723f03f297fffa62728b2-Stiebel.Eltron.ISG-7c3f43fccbf06c779de2b36cc2455d04.json.txt)

Edit: i masked the ip adress and port ;)

**Comment by jaysus82** [comment]
Anything new here? Maybe you can also add "Hz" as a unit for the ventilation speeds.

**Comment by Padanian** [comment]
Concerning this issue, do you have a local FET/FES/FEK installed in the house?
What model exactly?

**Comment by jaysus82** [comment]
I have this one:
https://www.tecalor.de/de/produkte/regelung_energiemanagement/zubehoer/tcr-comfort/tcr-comfort.html

**Comment by Padanian** [comment]
Yeah, there's a bug at line 152 in lwz_coordinator.py
I'll try to fix it

**Comment by jaysus82** [comment]
Nixe, will this automatically update or will I have to upload the fixed files manually?

**Comment by Padanian** [comment]
It will update once the maintainer release the new version. 
But you can try replace the file(s) manually too, if you want.

**Comment by jaysus82** [comment]
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/156689299/95ffdfa2-e879-4d96-b59a-3019b30129cc)
It's working, thank you very much! Is it possible that you add the unit "Hz" to the fan speeds? Do i have to open a new "issue" for that?

**Comment by Padanian** [comment]
Yes, please, so we can close this one.

**Comment by Padanian** [comment]
@pail23, closed fixed
