### ISSUE TITLE
HA 2024.1.3 Failure on Setup

### ISSUE THREAD

**Issue by martink2** [pail23/stiebel_eltron_isg_component#175]
## Version of the custom_component
2024.1.1
Homeassistant 2024.1.3

## Describe the bug

On initial Setup i added the IP of my ISG and the integration goes into "Failed to set up"

## Debug log
```text

2024-01-16 09:34:09.407 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Stiebel Eltron ISG for stiebel_eltron_isg
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stiebel_eltron_isg/__init__.py", line 98, in async_setup_entry
    if model >= 390
       ^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by martink2** [comment]
I can add another detail, I have added our second Heatpump also with an ISG just fine (ISG + WPL 09 ICS classic)

So the problem seems to be with the Combination of ISG  + WPE-I 33 H 400 Premium, is that model not supported yet ?

**Comment by Padanian** [comment]
WPE-I 33 are produced by Stiebel Eltron Sweden (former Thermia AB) and have a completely different and incompatible microprocessor and protocol.

**Comment by martink2** [comment]
@Padanian Thanks for taking a look into it, I also took a look at the modbus documentation from Stiebel and the registers 
are very different from the other models but at least modbus is supported and has a lot of information. 

Would it be feasible to add the registers to this repo or is the code too much tailored on the other controller generations to make this a useful adidtion ?

**Comment by Padanian** [comment]
In principle, everything is possible, but already recognising that the regulator is a WPM-G instead than a WPM3 or 4, requires quering three completely different registers (57, 58 and 59), instead than one (5002), because WPM-G does not offer controller identification.
That's really a new project to embark.

**Comment by Padanian** [comment]
@pail23 can be closed, can't fix.
