### ISSUE TITLE
Units for ventilation entities

### ISSUE THREAD

**Issue by jaysus82** [pail23/stiebel_eltron_isg_component#187]
This is not really an issue, but perhaps you can add units, as with the other measured values.

The units m³/h and Hz are missing for volume flow and fan speed.

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/156689299/4f401d7b-7a9f-4b3a-89d9-ed02c3be2b37)

**Comment by Padanian** [comment]
Note for self: modify the block https://github.com/pail23/stiebel_eltron_isg_component/blob/339a9f352ef1acd48d0d66f586b4adfa3bc85504/custom_components/stiebel_eltron_isg/sensor.py#L340

**Comment by pail23** [comment]
Should be solved in 2024.2

**Comment by jaysus82** [comment]
The units are there now, but I got an error msg after updating to 2024.2
[error_log.txt](https://github.com/pail23/stiebel_eltron_isg_component/files/14240354/error_log.txt)

**Comment by pail23** [comment]
@jaysus82 Which version of Home Assistant are you using? You need to have at lease 2024.2 installed.

**Comment by Padanian** [comment]
Works for me

**Comment by jaysus82** [comment]
> @jaysus82 Which version of Home Assistant are you using? You need to have at lease 2024.2 installed.

Thanks! I was running HA in a docker, now switched to VM, easier to update.
