### ISSUE TITLE
Device class missing for temperature sensors

### ISSUE THREAD

**Issue by xylone** [pail23/stiebel_eltron_isg_component#195]
When using a temperature sensor in a group, I get the message that one of them is missing a device_class.
I found that the code is indeed missing the device class for temperature sensors.
So I added it myself and tested it and it all works.

Can you please add the line
device_class=SensorDeviceClass.TEMPERATURE,
in:
https://github.com/pail23/stiebel_eltron_isg_component/blob/c76ed6af98303f2c5767f9bc318fb20ebc6f82c8/custom_components/stiebel_eltron_isg/sensor.py#L107

**Comment by pail23** [comment]
Should be solved in 2024.2
