### ISSUE TITLE
Humidity sensor stopped working with 2024.2

### ISSUE THREAD

**Issue by sti0** [pail23/stiebel_eltron_isg_component#201]
## Version of the custom_component
2024.2

## Describe the bug
Humidity sensor shows 0% after upgrading to 2024.2. After reverting to 2024.1.1 it works again. 
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/18382402/80ce3f8e-c50c-4c42-89f7-5ea7356aae7f)

My heatpump is a Tecalor THZ 8.5 flex cool.

**Comment by Padanian** [comment]
Might be related to #197 .
2024.02 changed base address.
@pail how do we tackle the issue?

**Comment by pail23** [comment]
@Padanian can this be related to this [change](https://github.com/pail23/stiebel_eltron_isg_component/commit/889dc7fa3181f55102f833cec57b841737ffb8e6)?
If this is the case we could used ACTUAL_HUMIDITY_HK1 and ACTUAL_HUMIDITY_HK2 instead of ACTUAL_HUMIDITY

@sti0 Is your heat pump  a WPM or a LWZ heatpump?

**Comment by sti0** [comment]
@pail23 I think my Tecalor one is equivalent to LWZ. Just noticed that there are also Humidity HK1-3 but I got no values for these ones

**Comment by Padanian** [comment]
> @Padanian can this be related to this [change](https://github.com/pail23/stiebel_eltron_isg_component/commit/889dc7fa3181f55102f833cec57b841737ffb8e6)? If this is the case we could used ACTUAL_HUMIDITY_HK1 (register 3) and ACTUAL_HUMIDITY_HK2 (register 6) instead of ACTUAL_HUMIDITY

Possibly. Of course, changing the variable declarations would be a break change.

**Comment by pail23** [comment]
I added "Humidity HK 1" and "Humidity HK 2" in the release 2024.2.1. 
@sti0 Could you please check if one of this is working?

**Comment by sti0** [comment]
@pail23 sorry for the late response. Just installed release 2024.2.2. And the humidity is now available as a new sensor ("Humidity HK 2") and gives me the right value.
Thanks for the fix.
