### ISSUE TITLE
Feature request: Compressor entity for cascaded heat pumps

### ISSUE THREAD

**Issue by andreabafile** [pail23/stiebel_eltron_isg_component#205]
For cascaded heat pumps systems, would be great to see "Compressor WP1", "Compressor WP2" and so on separately.
Now they're all combined in a single entity called Compressor.
Is it possible to open up?

Thank you

**Comment by Padanian** [comment]
WP1 and WP2 general data are already available. What other data would you like, specifically?

**Comment by andreabafile** [comment]
Compressor is just shown as one entity, combining WP1 and WP2 compressors.
I'd like to see 2 different entities, one entity for Compressor WP1 and a separate one for Compressor WP2.

**Comment by andreabafile** [comment]
by the way, compressors speed would also be very nice to have.

**Comment by Padanian** [comment]
#207 partly satisfies the requirement. 
Compressor starts and compressor speed are not transferred to modbus. Only available on canbus. Can't fix.

**Comment by pail23** [comment]
The additional entities from #207 are included in the release 2024.2.2. Please test the release.

**Comment by andreabafile** [comment]
Compressor by single HP working perfectly so far! Also nice to see all the charging pumps.
Thank you!
