### ISSUE TITLE
Adding heating curve rise

### ISSUE THREAD

**Issue by myHomeAssistantAdmin** [pail23/stiebel_eltron_isg_component#21]
Congratulation for your good home assistant integration.
I see you are up2date with it. 
My idea for next update:

Please implement the read/write parameter for the heating curve rise.
Think it is very important to show and change this parameter.

I think it works like:
- name: hp_ctl_heating_curve_rise_hc1
    register: 1503  #1504
    data_type: int
    scale: 0.01
    precision: 2
    register_type: holding
    hub: modbus_hp
    slave: 1

I found this in a other integration for STIEBEL ELTRON WPM3:
(https://gist.github.com/ntompson/e9e71e41137fc30fda9eee58b3e3b35c)

I hope it helps for you to implemented the heating curve rise.

**Comment by pail23** [comment]
Implemented in V0.7.0
