### ISSUE TITLE
All binaries always OFF

### ISSUE THREAD

**Issue by and1rockt** [pail23/stiebel_eltron_isg_component#221]
Dear community,

as title says, the binary sensor stiebel_eltron_isg_compressor shows always the same state: off. Same goes with all other binaries... All other sensors showing data as expected. Also the switches for SG-ready working just fine. 

Running all updated: the integration itself, HA 24.3.3

Any other users experiencing the same issues and may have a hand on how to fix this?

Thanks in advance!
[stiebel_eltron_isg-328b40abfa9e777b192c79f1d8ec65f1-Stiebel Eltron ISG-4cb2a8f436cc93a3b3923a5b6ff847ee.json](https://github.com/pail23/stiebel_eltron_isg_component/files/14802048/stiebel_eltron_isg-328b40abfa9e777b192c79f1d8ec65f1-Stiebel.Eltron.ISG-4cb2a8f436cc93a3b3923a5b6ff847ee.json)

**Comment by Padanian** [comment]
All digital statuses are bitcoded into modbus address 2501, so I wouldn't be surprised that if the register is faulty or buggy, all other digitals would not be working.
Have you got a WPL/HPA or a LWZ unit?
Anyone else can provide feedback or testing?

**Comment by and1rockt** [comment]
Thanks for the reply!
Its a WPL (Tecalor sub brand of Stiebel); strange also, when reading modbus with RMMS, I can see the bitcodes in the (correct) registers.. shall I post a quick dump of debugging of the addon - would that help?

thanks again!

**Comment by Padanian** [comment]
Anything helps

**Comment by and1rockt** [comment]
gotcha - kindly find attached; as far as my low skills tell me, there are some tibber and some template errors, but nothing from the ISG-addon  :/
[home-assistant_stiebel_eltron_isg_2024-03-30T10-05-41.129Z.log](https://github.com/pail23/stiebel_eltron_isg_component/files/14811480/home-assistant_stiebel_eltron_isg_2024-03-30T10-05-41.129Z.log)

**Comment by Padanian** [comment]
Yeah, plenty of errors, but nothing helping us.

**Comment by and1rockt** [comment]
was hoping, there is smthg helpful.. 
maybe also strange, that all of the mentioned binaries are shown as 'online', even though carrying 'unknown' as value..

**Comment by Padanian** [comment]
Are you familiar with modpoll software? Are you able to poll registers 2001 and 2501 via ethernet and post the results?

**Comment by and1rockt** [comment]
thank you!

I can offer values from modbus, if this helps?

**Comment by Padanian** [comment]
yes, please

**Comment by and1rockt** [comment]
![Screenshot 2024-04-12 142645](https://github.com/pail23/stiebel_eltron_isg_component/assets/67901111/ad4ccdc3-c1ab-433f-8542-66dfb331c149)

does that help?

**Comment by Padanian** [comment]
Yes, can you please export data of ranges 2000-2010 and 2500-2510

**Comment by and1rockt** [comment]
when trying to read 2000, I get an error..
![2505](https://github.com/pail23/stiebel_eltron_isg_component/assets/67901111/40d91fe6-14f7-4255-b7f1-a07611653a40)
![2509](https://github.com/pail23/stiebel_eltron_isg_component/assets/67901111/5df8d9d5-b7e9-433d-b1a4-96ab1e43b481)
![error](https://github.com/pail23/stiebel_eltron_isg_component/assets/67901111/79c43449-cf94-4110-95e6-bd61201a36b8)

**Comment by Padanian** [comment]
I'll look into it tonight or tomorrow.

**Comment by and1rockt** [comment]
> I'll look into it tonight or tomorrow.

thank you so much!

**Comment by Padanian** [comment]
Ok, can you please do it for 2501 when the compressor is running.
Bit n.7 need to be 1 when the compressor is running. Also please print the data in decimal, because counting the bits is complicated. For starting I don't understand why bit10 of 2503 is 1. It means the pump of buffer n.5 is running, but you don't have 5 buffers, do you?

**Comment by and1rockt** [comment]
> Ok, can you please do it for 2501 when the compressor is running. Bit n.7 need to be 1 when the compressor is running. Also please print the data in decimal, because counting the bits is complicated. For starting I don't understand why bit10 of 2503 is 1. It means the pump of buffer n.5 is running, but you don't have 5 buffers, do you?

will do, as soon as its running again, currently a lot of warm water in the pot ;)
And no, dont have more than 1 buffer.

**Comment by and1rockt** [comment]
Morning,

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/67901111/1706b561-994e-4b1d-b960-c8027589b6f1)
looks unchanged, even though the compressor is running atm:
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/67901111/acbce672-a822-4843-9ba9-444aad2d728b)

**Comment by Padanian** [comment]
So now we now it's not a component bug, it's possibly an ISG bug.
For what concerns the component, we can close this issue as "won't fix", but we now have two possibilities:
1) I contact STE in Germany to double check it and hope for the best. 
2) I have superAdmin access to all ISGs connected to servicewelt, and I can try update the firmware on your ISG. 
Both are long shots, too long possibly. If you want me to update your ISG and try again, PM me with your name and city and I will command update from remote.

**Comment by and1rockt** [comment]
much appreciated - thank you for the offer, will send a PM asap!

**Comment by Padanian** [comment]
Sorry for the late answer
Although GitHub removed the private messaging feature, there's still an alternative.
Copy and paste the next line into your browser: https://api.github.com/users/xxxxxxx/events/public
Replace the xxxxxxx in the URL with my username. Hit Enter.
Press Ctrl+F and search for “email”.
