### ISSUE TITLE
Adding reset heat pump

### ISSUE THREAD

**Issue by myHomeAssistantAdmin** [pail23/stiebel_eltron_isg_component#23]
Cause of an error in my heat pump I must reset my heat pump. 
But I can't do it with your integration.
So I hope it's posible for you to integrate a reset heat pump in your STIEBEL ELTRON integration.
In the STIEBEL ELTRON modbus dokumentation I see the modbus address '1520' value '3' for it.
I hope you can implement a reset heat pump with a next update in the future.

**Comment by pail23** [comment]
I have added a "reset heatpump" button, but I have not tested it since it's not clear to me what it does. If you don't mind, get the latests version of the main branch and test it. I have not yet created a release with this code.

**Comment by myHomeAssistantAdmin** [comment]
Sure, I'll be happy to do that, I know how the system should behave after a successful reset.
What exactly do I have to do with which file?
Sorry for the demand, I do not know myself here yet so well.

**Comment by pail23** [comment]
Ok. I have created the release v0.9.0 for testing. Just upgrade the component.

**Comment by myHomeAssistantAdmin** [comment]
Very good ! 
The reset of the heat pump works perfectly.
The heat pump was restarted as expected after pressing the reset button.
However, the heat pump did not (yet) have an error message for what the reset button should then actually help.
I am now waiting for our next heat pump error and try the reset button test again.
Give then again feedback.

**Comment by pail23** [comment]
Great to hear. Many thanks for testing. In case you want to reset the error list, there would be another possibility: Write 2 (insted of 3) into the register 1520. Is reseting the error list what you are looking for?

**Comment by myHomeAssistantAdmin** [comment]
Mhm, the reset of the error list should perhaps be better left before you lose important plant information.
I would rather do this directly on the system if necessary.

To get the error list also in the Home Assistant, that would be good. 
However, I have not yet found a mode code that contains the error list.

More important from my point of view would be the output of the last active error. 
I assume that this is in the modbus code 2507.
Should I open a separate ticket for you?

**Comment by pail23** [comment]
Yes, please open a separate issue for the last active error...

Thanks.

**Comment by pail23** [comment]
Looks like this one is solved by the implementation of the reset button. Please open a new issue in case there is something left.
