### ISSUE TITLE
Last active error

### ISSUE THREAD

**Issue by myHomeAssistantAdmin** [pail23/stiebel_eltron_isg_component#25]
From my point of view, it would be important to output the last active error from the error list, e.g. "8183 error unknown".
This message is then directly on the display if the heat pump has any problem and no longer works.
In this case a simple reset of the heat pump helps.
I suspect that this error text is in the modbus code 2507.

**Comment by pail23** [comment]
Implemented a first version in V0.10. Please test whether it displays the right error. In my case, I only get 32768, which probably means no error.

**Comment by xylone** [comment]
I can confirm.
HA reports Stiebel Eltron ISG Active Error: error 8163
This was the last reported error back in September 2022
So it can also be called 'Last reported error' ;-)

**Comment by pail23** [comment]
Implemented in V0.11.0
