### ISSUE TITLE
Temperature control per 0.5 degrees

### ISSUE THREAD

**Issue by xylone** [pail23/stiebel_eltron_isg_component#26]
Is it possible to control the set target temperature per 0.5 degrees?
<img width="433" alt="Scherm­afbeelding 2023-03-20 om 15 24 35" src="https://user-images.githubusercontent.com/2749350/226369739-a37aeb91-130f-4a04-86c4-f8c58ccd1b09.png">

Or is this something I can fix in HA?

**Comment by pail23** [comment]
Implemented 0.1 degrees in V0.10

**Comment by xylone** [comment]
Wow you are so quick! Thanks! Much appreciated!
Just one small question:
Can you add type: thermostat to these element, so they can be used as thermostats?
