### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by toessfrosch** [pail23/stiebel_eltron_isg_component#310]
Hello 
Looks very promising.
Is there a description of what is needed and how to connect it? 
Obviously it needs the ISG “Internet Service Gateway (ISG)” module, and with this I can connect the Stiebel Eltron heat pump directly (without cloud or internet connection) via Ethernet (Motbus/IP) to the Homeassistant. right?
Greetings Reto

**Comment by pail23** [comment]
Yes, that's correct: It does not need a cloude/internet connection. And yes: It is not properly described. I would highly appreciate a PR on the README.md file adding this information. :-)
