### ISSUE TITLE
deprecated warning in system log from home assistant 2024.11

### ISSUE THREAD

**Issue by lgusewski** [pail23/stiebel_eltron_isg_component#328]
Since Home Assistant 2024.11 i found this message in the log files:

###

Logger: homeassistant.core
Quelle: helpers/deprecation.py:222
Erstmals aufgetreten: 20:45:15 (1 Vorkommnisse)
Zuletzt protokolliert: 20:45:15

Config was used from stiebel_eltron_isg, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'stiebel_eltron_isg' custom integration

###

Is this project still alive?

**Comment by pail23** [comment]
fixed in version 2024.11
