### ISSUE TITLE
2024.11 crashing Home assistant

### ISSUE THREAD

**Issue by kaiwoknaj** [pail23/stiebel_eltron_isg_component#331]
I dont know why but this new version crashes my entire HA.
Had to roll back with my Backups.
HA crashes ~1 min after starting it up, I guess when Stiebel Eltron integration was loading.

**Comment by holsteiner-kiel** [comment]
For me it's syme. I can confirm that. With older versions I had no problems. Disabling the integration makes my HomeAssistant stable. Enabling it, let it crash.

**Comment by reneschuster** [comment]
Here it is working, I have no problems with the new version.

**Comment by Richy22B** [comment]
Same issue as OP. Noticed my heat pump stuck in DHW mode this morning then found Home Assistant not working. I've done some basic testing, but looks like whenever you try to change a temperature (DHW setpoint from Node Red in this case), it completely crashes HA.

**Comment by pail23** [comment]
Do you have any logs (ideally, you activate the debug logs) which can help to find the issue?

**Comment by Kunibert-007** [comment]
Same issue hier. With Version 2024.6 there is no problem. Unfortunately I haven't the logs, I'm happy HA is still running after hours without light and closed blinds at home :-D

**Comment by andreabafile** [comment]
Same issue for me today, upgrading to latest version.

Here below the error log:
Registratore: homeassistant.setup
Fonte: setup.py:334
Prima occorrenza: 23:48:46 (1 occorrenze)
Ultima registrazione: 23:48:46

Setup failed for custom integration 'stiebel_eltron_isg': Unable to import component: No module named 'homeassistant.core_config'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/stiebel_eltron_isg/__init__.py", line 14, in <module>
    from homeassistant.core_config import Config
ModuleNotFoundError: No module named 'homeassistant.core_config'

**Comment by Richy22B** [comment]
Yep mine crashing still even after update. This is my log...

[home-assistant_stiebel_eltron_isg_2024-11-26T19-44-08.951Z.log](https://github.com/user-attachments/files/17925105/home-assistant_stiebel_eltron_isg_2024-11-26T19-44-08.951Z.log)

**Comment by holsteiner-kiel** [comment]
Mine also crashing after newest Update. Back to second last Version.

**Comment by pail23** [comment]
@Richy22B I see a lot of error messages in the log, but none of them is related to the stiebel eltron integration.  Do you have a log where I can see an error related to the stiebel eltron integration? What is exactly happening,  when HA is crashing?

**Comment by holsteiner-kiel** [comment]
Sorry. There is no log with errors regarding Stiebel Eltron Integration.

Whats Happening? HA freezes conpletely. web Interface is not reachable and automations are not running any more.

**Comment by Richy22B** [comment]
@pail23 I think possibly because it is crashing HA completely when trying to call for temp change it is not registering on the log? The debug was active the whole time. Any way to retrieve this part specifically? I don't want to keep crashing my system as the whole house is literally stopping working (and wife going mental lol). 

When it crashed I was trying to call for a temp change in DHW tank setpoint. It showed an error on the Node Red node after it rebooted after the crash.
![error_in_node_red](https://github.com/user-attachments/assets/df7ae7d0-295a-4789-b909-b43e261ff86b)

**Comment by Richy22B** [comment]
Not sure if this helps too? Was all working fine before the updates. I can still read data just seems to crash on calls.
![node-red-call](https://github.com/user-attachments/assets/2ff83f26-b7ab-4449-9f91-6b80c3667a1d)

**Comment by jbr-42** [comment]
Could this be related to the change from synchronous to asynchronous calls for writing modbus registers with 2024.11?

**Comment by Mitchel85** [comment]
> 2024.11 doesn't work. Unable to load integration. Had to remove and downgrade it.

problem solved due to HA update. Had old HA version, but new stiebel eltron integration.

**Comment by cchhrriiss** [comment]
For the problem I am experiencing, I am now sure it is related to the Stiebel Eltron ISG integration somehow. Yesterday evening I was deactivating the Integration and HA worked fine over night. Today I enabled the integration from the HA-GUI and in the same moment HA crashed. So for now my only solution is to not use this integration and keep it disabled, which is very pitty.

**Comment by pail23** [comment]
I gave it another try to fix it in 2024.12

I can't reproduce the problem. Therefore I have added additional debug log entries. In case you still experience the problem, please activate debug logging for the integration and post the logs here.

**Comment by holsteiner-kiel** [comment]
Mine 2024.12 is not crashing any more on sending  commands.

Thank you very much!!!

**Comment by cchhrriiss** [comment]
Yesterday I installed 2024.12.0 (and also HA OS 14.0 and HA Core 2024.12). I could activate the integration and it did not crash over night. Therfore it seems to be fixed!! Thanks a lot for the support!!

**Comment by Richy22B** [comment]
> I gave it another try to fix it in 2024.12
> 
> I can't reproduce the problem. Therefore I have added additional debug log entries. In case you still experience the problem, please activate debug logging for the integration and post the logs here.

Seems to be fixed! Thanks for the support @pail23!
