### ISSUE TITLE
Write register

### ISSUE THREAD

**Issue by homefuzz-oz** [pail23/stiebel_eltron_isg_component#4]
Hi, many thanks for the integration. Works an absolute treat. I was wondering what your plans were, if any, regarding the additional Modbus parameters from the manual, especially the write types?

I am not a python expert, but if there are no plans, I can consider adding some of the remaining parameters. 

My idea is essentially that I don’t want to just read from the heat pump but also control it through HA.

**Comment by pail23** [comment]
At the moment, I don't have any intention to extend the integration as it covers my use cases. Nevertheless I would be happy to receive PRs for further extensions.

**Comment by homefuzz-oz** [comment]
Alright, thanks. Let me look into it then.
