### ISSUE TITLE
Climate Control for Heating Circuit 2

### ISSUE THREAD

**Issue by rabattcoupon** [pail23/stiebel_eltron_isg_component#56]
Hi, 

I really like your work. It is finally possible to monitor the Heat Pump. way better than in the ISG itself.

However, I have an issue with the plugin. It shows all the values for HK2 bit does not offer Climate Control like it does for HK1.  It looks like there is no entity for Climate_HK_2.

Regards

**Comment by pail23** [comment]
A first implementation is done in release 2023.5.3. Could you please check if this is what you intended to have? HK1 and HK2 are almost identical since only the target temperature values are different.

**Comment by rabattcoupon** [comment]
Awesome... Works exactly as expedcted. Thank you!
