### ISSUE TITLE
Circulation pump

### ISSUE THREAD

**Issue by rabattcoupon** [pail23/stiebel_eltron_isg_component#57]
Hi,

it would be great if you could add a circulation pump activation switch, since the WPM/ISG has only three times a day it can be programmed. With a switch like this one could optimize the use of the circulation pump, like it is already possible with the temperature. Your software could really help to get over the weaknesses of the WPM/ISG.

Thanks a lot!

**Comment by pail23** [comment]
Hi @rabattcoupon 

Currently I don't see a way how to do that. Please have a look at the [Modbus documenation](https://www.stiebel-eltron.ch/content/dam/ste/ch/de/downloads/kundenservice/smart-home/Modbus/Modbus%20Bedienungsanleitung.pdf) and let me know which register can be used to implement this switch.

**Comment by rabattcoupon** [comment]
Hi @pail23,

If I´m not mistaken, Read Register for status is on Page 8 => 2517 and Write Register should be 7012 on Page 19 whereas 47012 should be the address.

**Comment by northalpha** [comment]
this is possible like in #59 and it would be following "config"

modbus:

```
      - name: "LWZ BETRIEBSSTATUS"
        address: 2000
        slave: 1
        count: 1
        input_type: input
        data_type: uint16
```

template_sensor:

```
      - name: "LWZ Heizkreispumpe aktiv"
        state: "{{ states('sensor.lwz_betriebsstatus')|int|bitwise_and(1024) > 0 }}"
```

**Comment by pail23** [comment]
@northalpha The "LWZ Heizkreispumpe aktiv" is now available in the latest version as "Pump HK 1"

**Comment by rabattcoupon** [comment]
The circulation pump is for hot water and not for the heating system. In German it is "Zirkulationspumpe" not "Heizkreispumpe". It basically circulates warm water around the house to make sure you instantly get warm water. If you do not program it right, this massivly wastes energy.

**Comment by northalpha** [comment]
> @northalpha The "LWZ Heizkreispumpe aktiv" is now available in the latest version as "Pump HK 1"

can confirm that this is now working, you can sport when i made the update :)
![Bildschirmfoto 2023-05-17 um 15 33 59](https://github.com/pail23/stiebel_eltron_isg_component/assets/6721009/aa045a65-b2f9-4343-98df-52cf2e0bd97b)

@rabattcoupon the word is directly from the documentation and technical papers from stiebel. therefore i assume that there is this pump at least in my LWZ(!) 

For an WPM Type there it is a "ZIRKULATIONSPUMPE", maybe this is the confusion, that you want this switch for a WPM instead of a LWZ/LWA?

**Comment by rabattcoupon** [comment]
It does not work unfortunately => "This entity is unavailable"... It does not show a status. The writing part is not available, I think that is because of the unavailability of the entity.

**Comment by pail23** [comment]
@rabattcoupon Maybe I picked the wrong register. Would it be possible to upload 2 diagonostic information files: One when you know that the circulation pump is running and one when you know when the pump is not running. Maybe I can figure it out then.

**Comment by rabattcoupon** [comment]
Theoretically yes, how do I get these?

**Comment by pail23** [comment]
You need to select the 3 dots and then "Diagnoseinformationen herunterladen":
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/13279715/a611cee5-5238-45bc-a07e-6af884839c6f)

**Comment by rabattcoupon** [comment]
The (1) is with circulation running, the other is without.

[config_entry-stiebel_eltron_isg-e698717744e895d97c63d3f722191a77.json(1).txt.txt](https://github.com/pail23/stiebel_eltron_isg_component/files/11649405/config_entry-stiebel_eltron_isg-e698717744e895d97c63d3f722191a77.json.1.txt.txt)
[config_entry-stiebel_eltron_isg-e698717744e895d97c63d3f722191a77.json.txt.txt](https://github.com/pail23/stiebel_eltron_isg_component/files/11649407/config_entry-stiebel_eltron_isg-e698717744e895d97c63d3f722191a77.json.txt.txt)

**Comment by pail23** [comment]
@rabattcoupon I have not found any related register. :-(

**Comment by rabattcoupon** [comment]
Hi, I called Stiebel-Eltron... it took a while but I eventually got someone on the phone who knows how that stuff works. He was like: "Currently it is only possible to monitor the status. Switching it on and off is not possible, yet." It also looks like that Stiebel-Eltron does not have an official roadmap. :-(

**Comment by pail23** [comment]
Hi @rabattcoupon 

Many thanks for following up! I will close the issue. Let's open the issue again once the situation changes.
