### ISSUE TITLE
Switch for Stiebel Eltron ISG Is cooling (stiebel_eltron_isg_is_cooling)

### ISSUE THREAD

**Issue by Nusserdt** [pail23/stiebel_eltron_isg_component#70]
ISG Provide under

**Programme** > **Kühlzeit** (s=3,5)

time for active cooling. These times get ignored by my LWZ5 CS Premium (maybe this setting is not related to active cooling).

Unfortunately cooling function consumes about 0,7 kWh. Overnight it would takes a lot from the electrical storage.
Ofc cooling on night time is much more efficient, but on day time I have practically unlimited power from PV.

I would be great to enable/disable cooling with Home Assistant and an time based automation.

### If this is not possible to implement:

could it be possible to disable cooling indirectly over the **Operation Mode**? For example switch to Manual Operation Mode on night time?

Happy to hear from you!

**Comment by pail23** [comment]
I have not found any modbus register which could allow to disable cooling. Please provide my a hint in case you have found a related register.

What you could try: setting the target temperatures to a very high value during night. Maybe the cooling then stops because the target temperature is above the actual temperature.

**Comment by Nusserdt** [comment]
Hey @pail23 thanks for your reply. Worth a try to modify the temperatures, but Stiebel Eltron seems have some inconsistency with there cooling settings.

For cooling there exist own temperatures. In the cooling main menu you have the **HK-TEMP. KÜHLEN** 

<img width="1050" alt="image" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/35678990/6047e52b-be9d-4c17-bc73-7fbbe04c2832">

and in under **RAUMTEMPERATUREN HK1** you can find the **RAUMTEMP. TAG** (16,0 °C, this is not mirror to `HEIZEN` -> `RAUMTEMPERATUREN HK1` -> `RAUMTEMP. TAG`).

<img width="1043" alt="image" src="https://github.com/pail23/stiebel_eltron_isg_component/assets/35678990/98ce1981-67f1-4344-aa75-ed46f3ae19f8">

Both temperatures can't setted by extension. Additionally I also try already raise the **RAUMTEMP. NACHT** to prevent cooling at night, but Stiebel Eltron ignoring this setting. So I think the key temperature is under


`KÜHLEN` -> `KÜHLBETRIEB HK1` -> `HK-TEMP. KÜHLEN`

**Comment by pail23** [comment]
I have added the sensor for WPM mentioned by @guevara777 in the release 2023.8.1. The are named "Fan cooling ..." and "Area cooling ..."
