### ISSUE TITLE
operational status

### ISSUE THREAD

**Issue by spielkind1611** [pail23/stiebel_eltron_isg_component#71]
Hi,
First of all, thank you very much for your project!

But I have one wish if possible:
Is it possible to read out the entire register 2000. 

SWITCHING PROGRAM ENABLED B0
COMPRESSOR B1
HEATING B2
COOLING B3
DHW B4
ELECTRIC REHEATING B5
SERVICE B6
POWER-OFF B7
FILTER B8
VENTILATION B9
HEATING CIRCUIT PUMP B10
EVAPORATOR DEFROST B11
FILTER EXTRACT AIR B12
FILTER VENTILATION AIR B13
HEAT-UP PROGRAM B14

I hope you can help me.

Thanks Stefan

**Comment by pail23** [comment]
This should be implemented in 2023.6. Please test the new version.

**Comment by sti0** [comment]
Thanks for adding these sensors. I can confirm that they show up with 2023.6. But i noticed that the summer mode is unavailable (even was before 2023.6). I have a integral ventilation unit and I think in this case the summer mode needs to be fetched from a different register:
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/18382402/9ba3939d-60ce-451a-b44f-4d15e4e540f9)

**Comment by pail23** [comment]
The Summer Mode should be fixed in 2023.8

**Comment by sti0** [comment]
Thanks @pail23. Can confirm this is working with 2023.8
