### ISSUE TITLE
Add possiblitity for second device in one Home Assistant-Instance

### ISSUE THREAD

**Issue by guevara777** [pail23/stiebel_eltron_isg_component#8]
**Is your feature request related to a problem? Please describe.**
I do have to Stiebel-Eltron Heatpumps that i want to manage in one home assistant instance. Sadly this is not possible, because the device and the entities from the second device get the same unique_id´s that the first one gets.

**Describe the solution you'd like**
Please Add a "name" oder "device_number" to the config flow that ist added to the unique IDs so that it ist possible to add multiple instances.

**Describe alternatives you've considered**
I tried to fork your repository and do it my self, but i´m not skilled enough for that. :(

**Additional context**
I really LOVE your Stiebel Eltron ISG-integration. Thank you so much!

**Comment by pail23** [comment]
Could you please check if this is working for you in the new release 0.1.0?

**Comment by guevara777** [comment]
Thank you for your fast answer.

I found my own solution via modbus: in configuration.yaml. That works perfect.

To test you update i:
- freshly downloaded and installed version 0.1.0 via hacs
- removed my solution via configuration.yaml
- restarted home assistant
- startet adding both heat-pumps via you integration

This was the result:

![image](https://user-images.githubusercontent.com/29648553/211172579-7d436752-ee2a-4982-90d0-44e7601bbc60.png)

![image](https://user-images.githubusercontent.com/29648553/211172632-83a82b9c-fc36-4a88-a11d-66902c70abd4.png)

![image](https://user-images.githubusercontent.com/29648553/211172647-00738c7d-39e7-4ff3-83e7-8b1cf4aab51c.png)

I hope that helps

**Comment by pail23** [comment]
Version 0.6.0 implements better error messages. @guevara777 could you please check if you get no a better error message?

**Comment by guevara777** [comment]
Testet it with both my Heat Pumps and got NO errors because they could be added without a problem. Works like a charm.

**Comment by guevara777** [comment]
Thank you for adding this feature! ❤️
