### ISSUE TITLE
Adding set flow temperature for fan cooling (modbus reg 1516/7)

### ISSUE THREAD

**Issue by gargar69** [pail23/stiebel_eltron_isg_component#81]
I would like to change the cooling flow temperature ( COOLING_FLOW_TEMPERATURE_TARGET_CC1) which is modbus register 1517 (1516 for write I think).
I have read the preceding 5 bytes and following 2 bytes, loading each byte as a number and displaying the values as a,b,c,etc. The value for register 1515 and 1518 are shown as unavailable. This agrees with the fact that on the modbus sheet they are unavailable for WPM systems.
However when I change the value in the WPM console, it does not change (even on a restart of HASS) on the entity. Also when I change the entity in HASS it appears to change, but does not update the WPM.
I have configured the entity the same as the "comfort temperature for heating circuit 1’"as far as I know, so the step size and data type are the same.
I have also posted this on the HASS community. 
Any ideas would be gratefully received.
Thanks
GAR

**Comment by pail23** [comment]
The `Cooling Room Temperature Target` has been added in 2023.8

**Comment by gargar69** [comment]
Thanks Paul, but it is the 'cooling FLOW temperature target' that I am missing.

**Comment by pail23** [comment]
Added the entity in 2023.8.1. Please delete the Stiebel Eltron Configuration and re-add it since I had to change one entity name and id.

**Comment by gargar69** [comment]
Hi Paul. Thanks for the update. I have instaled 2023.8.1 and although the entity is shown it still chows unavailable. Using the Stiebel WPM the setting is available and is amendable. Hmm? 
Thanks GAR

**Comment by pail23** [comment]
I have extended the diagnosis information in the release 2023.10. Could you please download the diagnosis information and post them here?
