### ISSUE TITLE
[FEATURE] Check if API from new "MyStiebel"-App could be used for more information / controls

### ISSUE THREAD

**Issue by guevara777** [pail23/stiebel_eltron_isg_component#82]
**Is your feature request related to a problem? Please describe.**
The Stiebel Eltron ISG-Integration works flawless to control the heat pump. Thanks for your great work. The only thing missing for my is to control the schedules for "comfort" and "eco" in "program-mode". This is NOT possible via Modbus (due to lack of support for it by stiebel eltron).

**Describe the solution you'd like**
Stiebel Eltron made a [new MyStiebel-App](https://play.google.com/store/apps/details?id=com.stiebeleltron.mystiebel.v2) and released it last month. With this app you are able to control your heat pumps "eco" and "comfort"-temperatures remote (not only in your wifi, like in the old app) and you are able to view and set the schedule for "eco" and "comfort"-times in "program-mode". 

It would be nice to have the same options via home assistant. Maybe the API of the new app could be used for that!?

**Describe alternatives you've considered**
If it is not possible, we could still use the app to control the schedule. Just would be nice if it was also possible in home assistant.

**Comment by pail23** [comment]
Thanks for the hint. I did not find any documentation about the API the app is useing. In my case the app did not even find the ISG.

Do you have any documentation about the API the app is using?

**Comment by guevara777** [comment]
No, i don't know if there is an documentation of that API. If it is not availiable, maybe it could be solved via reverse Engineering. I´m (by far) not experienced enough to do that. Maybe you or someone how watches this "issue" could do that. Maybe Stiebel Eltron are willing to give the API-Documentation to developers, but if it is not published know if have little hope that they will do so.

**Comment by pail23** [comment]
I propose to close the issue. We can open it again once documentation will become available.
