### ISSUE TITLE
NHZ (electric booster) status is missing

### ISSUE THREAD

**Issue by msekoranja** [pail23/stiebel_eltron_isg_component#93]
Hi,

great integration! I was using manually coded modbus and I have decided to switch to your implementation. Much nicer!
However, I am missing a binary_status when NHZ (electric booster) is active, 2501/b3.

read_modbus_system_state() code just skips b3 decoding.

Any reason why it is not implemented?

Thank you,
Matej

**Comment by pail23** [comment]
the `NHZ Stages Running` entity has been added in 2023.8
