### ISSUE TITLE
modbus error: [connection] failed to connect[modbustcpclient(<IP>)]; retrying in background

### ISSUE THREAD

**Issue by chrissi5120** [pail23/stiebel_eltron_isg_component#97]
Hello everyone,

after upgrading from 0.1.0 to any recent version, I get the following error:

modbus error: [connection] failed to connect[modbustcpclient(<IP>)]; retrying in background

I tried to delete the custom_component folder and manually reinstall different versions but had no success.
As it seems, something breaks on TCP level and no communication is possible.

Any idea how I could debug that error or why it happens on a clean installation?

Best regards

Christoph

**Comment by pail23** [comment]
I think I have found and fixed an issue which might cause that problem. Could you please check the release 2023.8.1?

**Comment by chrissi5120** [comment]
you are the MAN,It works.. Thank you very, very much!
